# ===================================
#  Relation Behavior Config
# ===================================

users:
    label: Users
    list: ~/modules/backend/models/user/columns.yaml
    form: ~/modules/backend/models/user/fields.yaml
    view:
        toolbarButtons: add|remove
